### PR TITLE
add NextMoveTactic

### PR DESCRIPTION
**Pull request by mo271**
This uses stockfish to find a suitable next for "self"  move when proving a `ForcedWin`.  It assumes that a binary called `stockfish` is in your path.

I modeled it after the `polyrith` tactic, so you can click on `try this: move "foo"` and it will insert the suggestions. Right now it let's stockfish think for 0.1s,
but we could make that adjustable of course.

guess_next_move

### CODE REVIEW

**Comment by dwrensha** [comment]
I check this and and tried `lake build`. It failed with:
```console
✖ [384/386] Building Chess.Examples
trace: .> LEAN_PATH=././.lake/packages/batteries/.lake/build/lib:././.lake/packages/Qq/.lake/build/lib:././.lake/packages/aesop/.lake/build/lib:././.lake/packages/proofwidgets/.lake/build/lib:././.lake/packages/Cli/.lake/build/lib:././.lake/packages/importGraph/.lake/build/lib:././.lake/packages/mathlib/.lake/build/lib:././.lake/build/lib LD_LIBRARY_PATH= /home/dwrensha/.elan/toolchains/leanprover--lean4---v4.11.0/bin/lean -Dpp.unicode.fun=true -DautoImplicit=false -DrelaxedAutoImplicit=false ././././Chess/Examples.lean -R ./././. -o ././.lake/build/lib/Chess/Examples.olean -i ././.lake/build/lib/Chess/Examples.ilean -c ././.lake/build/ir/Chess/Examples.c --json
error: ././././Chess/Examples.lean:95:4: Script './scripts/get_next_move.py' exited with code 1:
error: Lean exited with code 1
Some required builds logged failures:
- Chess.Examples
error: build failed
```

I then did `sudo apt-get install stockfish` and tried again. This time it failed with:

```console
✖ [384/386] Building Chess.Examples
trace: .> LEAN_PATH=././.lake/packages/batteries/.lake/build/lib:././.lake/packages/Qq/.lake/build/lib:././.lake/packages/aesop/.lake/build/lib:././.lake/packages/proofwidgets/.lake/build/lib:././.lake/packages/Cli/.lake/build/lib:././.lake/packages/importGraph/.lake/build/lib:././.lake/packages/mathlib/.lake/build/lib:././.lake/build/lib LD_LIBRARY_PATH= /home/dwrensha/.elan/toolchains/leanprover--lean4---v4.11.0/bin/lean -Dpp.unicode.fun=true -DautoImplicit=false -DrelaxedAutoImplicit=false ././././Chess/Examples.lean -R ./././. -o ././.lake/build/lib/Chess/Examples.olean -i ././.lake/build/lib/Chess/Examples.ilean -c ././.lake/build/ir/Chess/Examples.c --json
error: ././././Chess/Examples.lean:95:4: Script './scripts/get_next_move.py' exited with code 1:
Traceback (most recent call last):
  File "/home/dwrensha/src/Chess.lean/./scripts/get_next_move.py", line 84, in <module>
    activate_and_run()
  File "/home/dwrensha/src/Chess.lean/./scripts/get_next_move.py", line 37, in activate_and_run
    install_package(VENV_DIR, 'python-chess')
  File "/home/dwrensha/src/Chess.lean/./scripts/get_next_move.py", line 24, in install_package
    subprocess.check_call([pip_executable, 'show', package], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.12/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dwrensha/src/Chess.lean/scripts/venv/bin/pip'
error: Lean exited with code 1
Some required builds logged failures:
- Chess.Examples
error: build failed
```


What do I need to do differently? And can we make the error messages better?

**Comment by mo271** [comment]
> I checked this branch out and tried `lake build`. It failed with:
> 
> ```
> ✖ [384/386] Building Chess.Examples
> trace: .> LEAN_PATH=././.lake/packages/batteries/.lake/build/lib:././.lake/packages/Qq/.lake/build/lib:././.lake/packages/aesop/.lake/build/lib:././.lake/packages/proofwidgets/.lake/build/lib:././.lake/packages/Cli/.lake/build/lib:././.lake/packages/importGraph/.lake/build/lib:././.lake/packages/mathlib/.lake/build/lib:././.lake/build/lib LD_LIBRARY_PATH= /home/dwrensha/.elan/toolchains/leanprover--lean4---v4.11.0/bin/lean -Dpp.unicode.fun=true -DautoImplicit=false -DrelaxedAutoImplicit=false ././././Chess/Examples.lean -R ./././. -o ././.lake/build/lib/Chess/Examples.olean -i ././.lake/build/lib/Chess/Examples.ilean -c ././.lake/build/ir/Chess/Examples.c --json
> error: ././././Chess/Examples.lean:95:4: Script './scripts/get_next_move.py' exited with code 1:
> error: Lean exited with code 1
> Some required builds logged failures:
> - Chess.Examples
> error: build failed
> ```
> 
> I then did `sudo apt-get install stockfish` and tried again. This time it failed with:
> 
> ```
> ✖ [384/386] Building Chess.Examples
> trace: .> LEAN_PATH=././.lake/packages/batteries/.lake/build/lib:././.lake/packages/Qq/.lake/build/lib:././.lake/packages/aesop/.lake/build/lib:././.lake/packages/proofwidgets/.lake/build/lib:././.lake/packages/Cli/.lake/build/lib:././.lake/packages/importGraph/.lake/build/lib:././.lake/packages/mathlib/.lake/build/lib:././.lake/build/lib LD_LIBRARY_PATH= /home/dwrensha/.elan/toolchains/leanprover--lean4---v4.11.0/bin/lean -Dpp.unicode.fun=true -DautoImplicit=false -DrelaxedAutoImplicit=false ././././Chess/Examples.lean -R ./././. -o ././.lake/build/lib/Chess/Examples.olean -i ././.lake/build/lib/Chess/Examples.ilean -c ././.lake/build/ir/Chess/Examples.c --json
> error: ././././Chess/Examples.lean:95:4: Script './scripts/get_next_move.py' exited with code 1:
> Traceback (most recent call last):
>   File "/home/dwrensha/src/Chess.lean/./scripts/get_next_move.py", line 84, in <module>
>     activate_and_run()
>   File "/home/dwrensha/src/Chess.lean/./scripts/get_next_move.py", line 37, in activate_and_run
>     install_package(VENV_DIR, 'python-chess')
>   File "/home/dwrensha/src/Chess.lean/./scripts/get_next_move.py", line 24, in install_package
>     subprocess.check_call([pip_executable, 'show', package], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
>   File "/usr/lib/python3.12/subprocess.py", line 408, in check_call
>     retcode = call(*popenargs, **kwargs)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/subprocess.py", line 389, in call
>     with Popen(*popenargs, **kwargs) as p:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/dwrensha/src/Chess.lean/scripts/venv/bin/pip'
> error: Lean exited with code 1
> Some required builds logged failures:
> - Chess.Examples
> error: build failed
> ```
> 
> What do I need to do differently? And can we make the error messages better?

I don't quite know what went wrong here. Somehow no `pip` binary? I modified it to look for `pip3` instead. Does it work now? I made great efforts not to force a user to change anything in their python setup, but create a `venv` instead.


I added ci to test building on linux, mac and windows. In windows after installing setting an environment variable was necessary, because the executable is not to be found under just the name `stockfish` like in linux and mac.

**Comment by dwrensha** [comment]
If I make this change:

```diff
--- a/scripts/get_next_move.py
+++ b/scripts/get_next_move.py
@@ -32,7 +32,12 @@ def get_pip_executable():
 def create_virtualenv(venv_path):
     """Creates a virtual environment if it doesn't exist."""
     if not os.path.isdir(venv_path):
-        venv.create(venv_path, with_pip=True)
+        try:
+            venv.create(venv_path, with_pip=True)
+        except SystemExit as e:
+            print("failed to make venv", file=sys.stderr)
+            print(e, file=sys.stderr)
+            sys.exit(2)
```

Then I see this error:
```console
error: ././././Chess/Examples.lean:95:4: Script './scripts/get_next_move.py' exited with code 2:
failed to make venv
1

```

**Comment by mo271** [comment]
Mmh.
Is this about permissions? What is the output of
```
ls -ld /home/dwrensha/src/Chess.lean/scripts/
```

If you create is manually with 
```
python3 -m venv /home/dwrensha/src/Chess.lean/scripts/venv

```
is this also failing? If yes, what is the error (and python version?)?

**Comment by dwrensha** [comment]
```console
$ ls -ld /home/dwrensha/src/Chess.lean/scripts/
drwxrwxr-x 3 dwrensha dwrensha 4096 Sep 30 09:35 /home/dwrensha/src/Chess.lean/scripts/
```

aha:
```console
$ python3 -m venv /home/dwrensha/src/Chess.lean/scripts/venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.12-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: /home/dwrensha/src/Chess.lean/scripts/venv/bin/python3
```

**Comment by dwrensha** [comment]
I think if you can improve the error handling here, or at least add a bit more to README, then I would feel okay merging this.

**Comment by dwrensha** [comment]
Maybe the example that uses the new tactic should move out of the main library (perhaps into a new test target), so that `lake build` of the main target does not need python in order to succeed.

**Comment by mo271** [comment]
ok, improved error handling, more explanation to README and moved NextMove stuff to different file, and out of Chess.lean.

**Comment by dwrensha** [comment]
Thanks!

**Pull request merged**
